import { Button, Flex } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button>Button</Button>
      <Flex justify="center">
        <Button>Button</Button>
        <Button>Button</Button>
        <Button>Button</Button>
      </Flex>
    </div>
  );
};

export default Home;
